"use client";

import { useMemo, useState, useTransition } from "react";
import { PanelRightClose, PanelRightOpen, RotateCcw, Save } from "lucide-react";
import { applyProfileCssAction } from "@/app/actions";

type GeneratorOptions = {
  pageBackground: string;
  contentBackground: string;
  boxTitleBackground: string;
  textColor: string;
  fontFamily: string;
  contentWidth: string;
};

const DEFAULT_OPTIONS: GeneratorOptions = {
  pageBackground: "#e5e7eb",
  contentBackground: "#ffffff",
  boxTitleBackground: "#6699cc",
  textColor: "#000000",
  fontFamily: "system-ui, sans-serif",
  contentWidth: "960px",
};

const OPTION_LABELS: Record<keyof GeneratorOptions, string> = {
  pageBackground: "Page background",
  contentBackground: "Profile background",
  boxTitleBackground: "Section headers",
  textColor: "Text color",
  fontFamily: "Font family",
  contentWidth: "Profile width",
};

function buildControlCss(options: GeneratorOptions): string {
  return `/* Generated by the profile layout generator */
.profile-page {
  background: ${options.pageBackground};
  color: ${options.textColor};
  font-family: ${options.fontFamily};
}

.profile-content {
  max-width: ${options.contentWidth};
  background: ${options.contentBackground};
}

.profile-page .box-title {
  background: ${options.boxTitleBackground} !important;
}

.profile-page .box-content {
  background: color-mix(in srgb, ${options.contentBackground} 94%, #ffffff) !important;
}
`;
}

function sanitizeStyleText(css: string): string {
  return css.replace(/<\/style/gi, "<\\/style");
}

export default function ProfileGenerator({
  children,
  existingCss,
}: {
  children: React.ReactNode;
  existingCss: boolean;
}) {
  const [isOpen, setIsOpen] = useState(true);
  const [options, setOptions] = useState(DEFAULT_OPTIONS);
  const [customCss, setCustomCss] = useState("");
  const [status, setStatus] = useState("");
  const [error, setError] = useState("");
  const [pending, startTransition] = useTransition();

  const generatedCss = useMemo(() => buildControlCss(options), [options]);
  const previewCss = `${generatedCss}\n${customCss}`;

  function updateOption<K extends keyof GeneratorOptions>(
    key: K,
    value: GeneratorOptions[K],
  ) {
    setOptions((current) => ({ ...current, [key]: value }));
    setStatus("");
  }

  function resetControls() {
    setOptions(DEFAULT_OPTIONS);
    setCustomCss("");
    setStatus("");
    setError("");
  }

  function applyToProfile() {
    if (
      existingCss &&
      !window.confirm(
        "Your profile already has custom CSS. Applying this layout will override it. Continue?",
      )
    ) {
      return;
    }

    const formData = new FormData();
    formData.set("customCss", previewCss);
    setStatus("");
    setError("");
    startTransition(async () => {
      const result = await applyProfileCssAction(formData);
      if (result.error) setError(result.error);
      else setStatus("Applied to your profile.");
    });
  }

  return (
    <div className={`profile-generator ${isOpen ? "is-sidebar-open" : ""}`}>
      <style>{sanitizeStyleText(previewCss)}</style>
      <div className="profile-generator-preview">{children}</div>

      <aside className="profile-generator-sidebar" aria-label="Profile layout controls">
        <div className="profile-generator-sidebar-header">
          <div>
            <span className="profile-generator-kicker">LIVE EDITOR</span>
            <h1>Profile layout</h1>
          </div>
          <button
            type="button"
            className="profile-generator-icon-button"
            onClick={() => setIsOpen(false)}
            title="Collapse layout controls"
            aria-label="Collapse layout controls"
          >
            <PanelRightClose size={16} aria-hidden="true" />
          </button>
        </div>

        <div className="profile-generator-sidebar-content">
          <div className="profile-generator-section">
            <div className="profile-generator-section-heading">
              <h2>Quick styling</h2>
              <button
                type="button"
                className="profile-generator-reset"
                onClick={resetControls}
                title="Reset layout controls"
              >
                <RotateCcw size={13} aria-hidden="true" />
                Reset
              </button>
            </div>
            <div className="profile-generator-control-grid">
              {(["pageBackground", "contentBackground", "boxTitleBackground", "textColor"] as const).map(
                (key) => (
                  <label key={key} className="profile-generator-color-control">
                    <span>{OPTION_LABELS[key]}</span>
                    <span className="profile-generator-color-row">
                      <input
                        type="color"
                        value={options[key]}
                        onChange={(event) => updateOption(key, event.target.value)}
                        aria-label={OPTION_LABELS[key]}
                      />
                      <code>{options[key]}</code>
                    </span>
                  </label>
                ),
              )}
            </div>

            <label className="profile-generator-field">
              <span>{OPTION_LABELS.fontFamily}</span>
              <select
                className="input"
                value={options.fontFamily}
                onChange={(event) => updateOption("fontFamily", event.target.value)}
              >
                <option value="system-ui, sans-serif">System sans</option>
                <option value="Georgia, serif">Georgia</option>
                <option value="Verdana, sans-serif">Verdana</option>
                <option value="'Courier New', monospace">Courier New</option>
              </select>
            </label>

            <label className="profile-generator-field">
              <span>{OPTION_LABELS.contentWidth}</span>
              <select
                className="input"
                value={options.contentWidth}
                onChange={(event) => updateOption("contentWidth", event.target.value)}
              >
                <option value="760px">Compact (760px)</option>
                <option value="960px">Classic (960px)</option>
                <option value="1100px">Wide (1100px)</option>
                <option value="100%">Full width</option>
              </select>
            </label>
          </div>

          <div className="profile-generator-section">
            <label className="profile-generator-field" htmlFor="generator-custom-css">
              <span>Custom CSS</span>
              <textarea
                id="generator-custom-css"
                className="input profile-generator-css-input"
                value={customCss}
                onChange={(event) => {
                  setCustomCss(event.target.value.slice(0, 12000));
                  setStatus("");
                }}
                maxLength={12000}
                rows={11}
                spellCheck={false}
                placeholder="/* Add advanced CSS here */\n.profile-page .profile-photo {\n  border-radius: 50%;\n}"
              />
            </label>
            <p className="profile-generator-hint">
              Use the profile class names from Edit Profile for more detailed styling.
            </p>
          </div>

          {existingCss && (
            <div className="profile-generator-warning" role="alert">
              <strong>Warning:</strong> this profile already has custom CSS. Applying this layout will override the current CSS.
            </div>
          )}

          {error && <div className="profile-generator-error" role="alert">{error}</div>}
          {status && <div className="profile-generator-success" role="status">{status}</div>}

          <button
            type="button"
            className="btn profile-generator-apply"
            onClick={applyToProfile}
            disabled={pending}
          >
            <Save size={15} aria-hidden="true" />
            {pending ? "Applying..." : "Apply to my profile"}
          </button>
        </div>
      </aside>

      {!isOpen && (
        <button
          type="button"
          className="profile-generator-open-button"
          onClick={() => setIsOpen(true)}
          title="Open layout controls"
          aria-label="Open layout controls"
        >
          <PanelRightOpen size={17} aria-hidden="true" />
          <span>Layout controls</span>
        </button>
      )}
    </div>
  );
}
