import { describe, expect, it } from "vitest";
import {
    buildControlCss,
    loadOptionsFromCss,
} from "./ProfileGenerator";

const GENERATED_MARKER = "/* Generated by the profile layout generator */";

describe("loadOptionsFromCss", () => {
    it("returns defaults and keeps everything when there is no generated section", () => {
        const css = ".profile-page .photo { border-radius: 50%; }";
        const result = loadOptionsFromCss(css);

        expect(result.options.pageBackground).toBe("#e5e7eb");
        expect(result.options.textColor).toBe("#000000");
        expect(result.options.useFontFamily).toBe(false);
        expect(result.customCss).toBe(css);
    });

    it("parses generated controls back into options", () => {
        const css = [
            GENERATED_MARKER,
            ".profile-page {",
            "  background-color: #112233;",
            '  background-image: url("https://example.com/bg.jpg");',
            "  background-position: center center;",
            "  background-size: cover;",
            "  background-repeat: no-repeat;",
            "  background-attachment: fixed;",
            "  color: #ffffff;",
            "  font-family: Georgia, serif;",
            "}",
            ".profile-content {",
            "  max-width: 760px;",
            "  background: #aabbcc;",
            "  border-color: #112233 !important;",
            "  border-width: 2px !important;",
            "  border-style: dashed !important;",
            "  border-radius: 8px !important;",
            "}",
            ".profile-page .box {",
            "  border-color: #112233 !important;",
            "  border-width: 2px !important;",
            "  border-style: dashed !important;",
            "  border-radius: 8px !important;",
            "}",
            ".profile-page .box-title {",
            "  background: #334455 !important;",
            "}",
            ".profile-page .box-content {",
            "  background: color-mix(in srgb, #aabbcc 94%, #ffffff) !important;",
            "}",
        ].join("\n");

        const result = loadOptionsFromCss(css);

        expect(result.options.pageBackground).toBe("#112233");
        expect(result.options.backgroundImage).toBe(
            "https://example.com/bg.jpg",
        );
        expect(result.options.backgroundPosition).toBe("center center");
        expect(result.options.backgroundSize).toBe("cover");
        expect(result.options.backgroundRepeat).toBe("no-repeat");
        expect(result.options.backgroundAttachment).toBe("fixed");
        expect(result.options.textColor).toBe("#ffffff");
        expect(result.options.useFontFamily).toBe(true);
        expect(result.options.fontFamily).toBe("Georgia, serif");
        expect(result.options.useContentWidth).toBe(true);
        expect(result.options.contentWidth).toBe("760px");
        expect(result.options.contentBackground).toBe("#aabbcc");
        expect(result.options.borderColor).toBe("#112233");
        expect(result.options.borderWidth).toBe("2px");
        expect(result.options.borderStyle).toBe("dashed");
        expect(result.options.borderRadius).toBe("8px");
        expect(result.options.boxTitleBackground).toBe("#334455");
        expect(result.customCss).toBe("");
    });

    it("keeps css that does not match any input", () => {
        const css = [
            GENERATED_MARKER,
            ".profile-page {",
            "  background-color: #112233;",
            "  margin-top: 10px;",
            "  color: red;",
            "}",
            ".profile-content {",
            "  background: #aabbcc;",
            "  border-radius: 8px !important;",
            "}",
            ".profile-page .box {",
            "  border-width: 5px !important;",
            "}",
            ".profile-page .box-title {",
            "  background: #334455 !important;",
            "}",
            ".profile-page .box-content {",
            "  background: color-mix(in srgb, #aabbcc 94%, #ffffff) !important;",
            "}",
            ".profile-page .photo { border-radius: 50%; }",
        ].join("\n");

        const result = loadOptionsFromCss(css);

        expect(result.options.pageBackground).toBe("#112233");
        expect(result.options.contentBackground).toBe("#aabbcc");
        expect(result.options.borderRadius).toBe("8px");
        // Named color cannot be shown in a color input, so it stays in css.
        expect(result.options.textColor).toBe("#000000");
        expect(result.customCss).toContain("margin-top: 10px");
        expect(result.customCss).toContain("color: red");
        // Box border differs from the .profile-content border, so it is kept.
        expect(result.customCss).toContain("border-width: 5px");
        expect(result.customCss).toContain(
            ".profile-page .photo { border-radius: 50%; }",
        );
    });

    it("round-trips generated css", () => {
        const options = {
            pageBackground: "#112233",
            backgroundImage: "https://example.com/bg.jpg",
            backgroundPosition: "left top",
            backgroundSize: "contain",
            backgroundRepeat: "repeat-x",
            backgroundAttachment: "scroll",
            contentBackground: "#aabbcc",
            boxTitleBackground: "#334455",
            textColor: "#ffffff",
            useFontFamily: true,
            fontFamily: "Verdana, sans-serif",
            useContentWidth: true,
            contentWidth: "100%",
            borderColor: "#112233",
            borderWidth: "3px",
            borderStyle: "double",
            borderRadius: "16px",
        } as const;

        const customCss = ".profile-page .photo { border-radius: 50%; }";

        const css = `${buildControlCss(options)}\n${customCss}`;
        const result = loadOptionsFromCss(css);

        expect(result.options).toEqual(options);
        expect(result.customCss).toBe(customCss);
    });
});