"use client";

import { useEffect, useMemo, useRef, useState, useTransition } from "react";
import { PanelRightClose, PanelRightOpen, RotateCcw, Save } from "lucide-react";
import { applyProfileCssAction } from "@/app/actions";

type GeneratorOptions = {
    pageBackground: string;
    backgroundImage: string;
    backgroundPosition: string;
    backgroundSize: string;
    backgroundRepeat: string;
    backgroundAttachment: string;
    contentBackground: string;
    boxTitleBackground: string;
    textColor: string;
    useFontFamily: boolean;
    fontFamily: string;
    useContentWidth: boolean;
    contentWidth: string;
    borderColor: string;
    borderWidth: string;
    borderStyle: string;
    borderRadius: string;
};

const DEFAULT_OPTIONS: GeneratorOptions = {
    pageBackground: "#e5e7eb",
    backgroundImage: "",
    backgroundPosition: "center center",
    backgroundSize: "cover",
    backgroundRepeat: "no-repeat",
    backgroundAttachment: "fixed",
    contentBackground: "#ffffff",
    boxTitleBackground: "#6699cc",
    textColor: "#000000",
    useFontFamily: false,
    fontFamily: "system-ui, sans-serif",
    useContentWidth: false,
    contentWidth: "960px",
    borderColor: "#6699cc",
    borderWidth: "1px",
    borderStyle: "solid",
    borderRadius: "0px",
};

const OPTION_LABELS: Record<keyof GeneratorOptions, string> = {
    pageBackground: "Page background",
    backgroundImage: "Background image URL",
    backgroundPosition: "Image position",
    backgroundSize: "Image size",
    backgroundRepeat: "Image repeat",
    backgroundAttachment: "Image attachment",
    contentBackground: "Profile background",
    boxTitleBackground: "Section headers",
    textColor: "Text color",
    useFontFamily: "Use font family",
    fontFamily: "Font family",
    useContentWidth: "Use profile width",
    contentWidth: "Profile width",
    borderColor: "Border color",
    borderWidth: "Border width",
    borderStyle: "Border style",
    borderRadius: "Border radius",
};

function escapeCssUrl(url: string): string {
    return url.replace(/["\\\r\n]/g, (character) => `\\${character}`);
}

function buildControlCss(options: GeneratorOptions): string {
    const backgroundImage = options.backgroundImage.trim()
        ? `  background-image: url("${escapeCssUrl(options.backgroundImage.trim())}");\n`
        : "";
    const fontFamily = options.useFontFamily
        ? `  font-family: ${options.fontFamily};\n`
        : "";
    const contentWidth = options.useContentWidth
        ? `  max-width: ${options.contentWidth};\n`
        : "";

    return `/* Generated by the profile layout generator */
.profile-page {
  background-color: ${options.pageBackground};
${backgroundImage}  background-position: ${options.backgroundPosition};
  background-size: ${options.backgroundSize};
  background-repeat: ${options.backgroundRepeat};
  background-attachment: ${options.backgroundAttachment};
  color: ${options.textColor};
${fontFamily}}

.profile-content {
${contentWidth}  background: ${options.contentBackground};
  border-color: ${options.borderColor} !important;
  border-width: ${options.borderWidth} !important;
  border-style: ${options.borderStyle} !important;
  border-radius: ${options.borderRadius} !important;
}

.profile-page .box {
  border-color: ${options.borderColor} !important;
  border-width: ${options.borderWidth} !important;
  border-style: ${options.borderStyle} !important;
  border-radius: ${options.borderRadius} !important;
}

.profile-page .box-title {
  background: ${options.boxTitleBackground} !important;
}

.profile-page .box-content {
  background: color-mix(in srgb, ${options.contentBackground} 94%, #ffffff) !important;
}
`;
}

function sanitizeStyleText(css: string): string {
    return css.replace(/<\/style/gi, "<\\/style");
}

export default function ProfileGenerator({
    children,
    existingCss,
}: {
    children: React.ReactNode;
    existingCss: boolean;
}) {
    const generatorRef = useRef<HTMLDivElement>(null);
    const [isOpen, setIsOpen] = useState(true);
    const [options, setOptions] = useState(DEFAULT_OPTIONS);
    const [customCss, setCustomCss] = useState("");
    const [status, setStatus] = useState("");
    const [error, setError] = useState("");
    const [pending, startTransition] = useTransition();

    const generatedCss = useMemo(() => buildControlCss(options), [options]);
    const previewCss = `${generatedCss}\n${customCss}`;

    useEffect(() => {
        const header = document.querySelector("header");
        const generator = generatorRef.current;
        if (!header || !generator) return;

        const updateHeaderHeight = () => {
            generator.style.setProperty(
                "--profile-generator-top",
                `${header.getBoundingClientRect().height}px`,
            );
        };

        updateHeaderHeight();
        const observer = new ResizeObserver(updateHeaderHeight);
        observer.observe(header);
        window.addEventListener("resize", updateHeaderHeight);

        return () => {
            observer.disconnect();
            window.removeEventListener("resize", updateHeaderHeight);
        };
    }, []);

    function updateOption<K extends keyof GeneratorOptions>(
        key: K,
        value: GeneratorOptions[K],
    ) {
        setOptions((current) => ({ ...current, [key]: value }));
        setStatus("");
    }

    function resetControls() {
        setOptions(DEFAULT_OPTIONS);
        setCustomCss("");
        setStatus("");
        setError("");
    }

    function applyToProfile() {
        if (
            existingCss &&
            !window.confirm(
                "Your profile already has custom CSS. Applying this layout will override it. Continue?",
            )
        ) {
            return;
        }

        const formData = new FormData();
        formData.set("customCss", previewCss);
        setStatus("");
        setError("");
        startTransition(async () => {
            const result = await applyProfileCssAction(formData);
            if (result.error) setError(result.error);
            else setStatus("Applied to your profile.");
        });
    }

    return (
        <div
            ref={generatorRef}
            className={`profile-generator ${isOpen ? "is-sidebar-open" : ""}`}
        >
            <style>{sanitizeStyleText(previewCss)}</style>
            <div className="profile-generator-preview">{children}</div>

            <aside
                className="profile-generator-sidebar"
                aria-label="Profile layout controls"
            >
                <div className="profile-generator-sidebar-header">
                    <div>
                        <span className="profile-generator-kicker">
                            LIVE EDITOR
                        </span>
                        <h1>Profile layout</h1>
                    </div>
                    <button
                        type="button"
                        className="profile-generator-icon-button"
                        onClick={() => setIsOpen(false)}
                        title="Hide editor"
                        aria-label="Hide editor"
                    >
                        <PanelRightClose size={16} aria-hidden="true" />
                        <span>Hide editor</span>
                    </button>
                </div>

                <div className="profile-generator-sidebar-content">
                    <div className="profile-generator-section">
                        <div className="profile-generator-section-heading">
                            <h2>Quick styling</h2>
                            <button
                                type="button"
                                className="profile-generator-reset"
                                onClick={resetControls}
                                title="Reset layout controls"
                            >
                                <RotateCcw size={13} aria-hidden="true" />
                                Reset
                            </button>
                        </div>
                        <div className="profile-generator-control-grid">
                            {(
                                [
                                    "pageBackground",
                                    "contentBackground",
                                    "boxTitleBackground",
                                    "textColor",
                                    "borderColor",
                                ] as const
                            ).map((key) => (
                                <label
                                    key={key}
                                    className="profile-generator-color-control"
                                >
                                    <span>{OPTION_LABELS[key]}</span>
                                    <span className="profile-generator-color-row">
                                        <input
                                            type="color"
                                            value={options[key]}
                                            onChange={(event) =>
                                                updateOption(
                                                    key,
                                                    event.target.value,
                                                )
                                            }
                                            aria-label={OPTION_LABELS[key]}
                                        />
                                        <code>{options[key]}</code>
                                    </span>
                                </label>
                            ))}
                        </div>

                        <div className="profile-generator-subsection">
                            <label className="profile-generator-check">
                                <input
                                    type="checkbox"
                                    checked={options.useFontFamily}
                                    onChange={(event) =>
                                        updateOption(
                                            "useFontFamily",
                                            event.target.checked,
                                        )
                                    }
                                />
                                <span>{OPTION_LABELS.useFontFamily}</span>
                            </label>
                            {options.useFontFamily && (
                                <label className="profile-generator-field">
                                    <span>{OPTION_LABELS.fontFamily}</span>
                                    <select
                                        className="input"
                                        value={options.fontFamily}
                                        onChange={(event) =>
                                            updateOption(
                                                "fontFamily",
                                                event.target.value,
                                            )
                                        }
                                    >
                                        <option value="system-ui, sans-serif">
                                            System sans
                                        </option>
                                        <option value="Georgia, serif">
                                            Georgia
                                        </option>
                                        <option value="Verdana, sans-serif">
                                            Verdana
                                        </option>
                                        <option value="'Courier New', monospace">
                                            Courier New
                                        </option>
                                    </select>
                                </label>
                            )}
                        </div>

                        <div className="profile-generator-subsection">
                            <label className="profile-generator-check">
                                <input
                                    type="checkbox"
                                    checked={options.useContentWidth}
                                    onChange={(event) =>
                                        updateOption(
                                            "useContentWidth",
                                            event.target.checked,
                                        )
                                    }
                                />
                                <span>{OPTION_LABELS.useContentWidth}</span>
                            </label>
                            {options.useContentWidth && (
                                <label className="profile-generator-field">
                                    <span>{OPTION_LABELS.contentWidth}</span>
                                    <select
                                        className="input"
                                        value={options.contentWidth}
                                        onChange={(event) =>
                                            updateOption(
                                                "contentWidth",
                                                event.target.value,
                                            )
                                        }
                                    >
                                        <option value="760px">
                                            Compact (760px)
                                        </option>
                                        <option value="960px">
                                            Classic (960px)
                                        </option>
                                        <option value="1100px">
                                            Wide (1100px)
                                        </option>
                                        <option value="100%">Full width</option>
                                    </select>
                                </label>
                            )}
                        </div>

                        <div className="profile-generator-subsection">
                            <h3>Border styling</h3>
                            <div className="profile-generator-border-grid">
                                <label className="profile-generator-field">
                                    <span>{OPTION_LABELS.borderWidth}</span>
                                    <select
                                        className="input"
                                        value={options.borderWidth}
                                        onChange={(event) =>
                                            updateOption(
                                                "borderWidth",
                                                event.target.value,
                                            )
                                        }
                                    >
                                        <option value="0px">None</option>
                                        <option value="1px">1px</option>
                                        <option value="2px">2px</option>
                                        <option value="3px">3px</option>
                                        <option value="4px">4px</option>
                                    </select>
                                </label>
                                <label className="profile-generator-field">
                                    <span>{OPTION_LABELS.borderStyle}</span>
                                    <select
                                        className="input"
                                        value={options.borderStyle}
                                        onChange={(event) =>
                                            updateOption(
                                                "borderStyle",
                                                event.target.value,
                                            )
                                        }
                                    >
                                        <option value="solid">Solid</option>
                                        <option value="dashed">Dashed</option>
                                        <option value="dotted">Dotted</option>
                                        <option value="double">Double</option>
                                    </select>
                                </label>
                                {/* <label className="profile-generator-field">
                                    <span>{OPTION_LABELS.borderRadius}</span>
                                    <select
                                        className="input"
                                        value={options.borderRadius}
                                        onChange={(event) =>
                                            updateOption(
                                                "borderRadius",
                                                event.target.value,
                                            )
                                        }
                                    >
                                        <option value="0px">Square</option>
                                        <option value="4px">Small</option>
                                        <option value="8px">Medium</option>
                                        <option value="16px">Large</option>
                                        <option value="999px">Pill</option>
                                    </select>
                                </label> */}
                            </div>
                        </div>
                    </div>

                    <div className="profile-generator-section">
                        <div className="profile-generator-section-heading">
                            <h2>Page background</h2>
                        </div>
                        <label className="profile-generator-field">
                            <span>{OPTION_LABELS.backgroundImage}</span>
                            <input
                                className="input"
                                type="url"
                                value={options.backgroundImage}
                                onChange={(event) =>
                                    updateOption(
                                        "backgroundImage",
                                        event.target.value,
                                    )
                                }
                                placeholder="https://example.com/background.jpg"
                                maxLength={500}
                            />
                        </label>
                        <div className="profile-generator-border-grid profile-generator-background-settings">
                            <label className="profile-generator-field">
                                <span>{OPTION_LABELS.backgroundPosition}</span>
                                <select
                                    className="input"
                                    value={options.backgroundPosition}
                                    onChange={(event) =>
                                        updateOption(
                                            "backgroundPosition",
                                            event.target.value,
                                        )
                                    }
                                >
                                    <option value="center top">
                                        Top center
                                    </option>
                                    <option value="center center">
                                        Center
                                    </option>
                                    <option value="left top">Top left</option>
                                    <option value="right top">Top right</option>
                                    <option value="center bottom">
                                        Bottom center
                                    </option>
                                </select>
                            </label>
                            <label className="profile-generator-field">
                                <span>{OPTION_LABELS.backgroundSize}</span>
                                <select
                                    className="input"
                                    value={options.backgroundSize}
                                    onChange={(event) =>
                                        updateOption(
                                            "backgroundSize",
                                            event.target.value,
                                        )
                                    }
                                >
                                    <option value="cover">Cover</option>
                                    <option value="contain">Contain</option>
                                    <option value="auto">Original size</option>
                                    <option value="100% auto">
                                        Stretch width
                                    </option>
                                </select>
                            </label>
                            <label className="profile-generator-field">
                                <span>{OPTION_LABELS.backgroundRepeat}</span>
                                <select
                                    className="input"
                                    value={options.backgroundRepeat}
                                    onChange={(event) =>
                                        updateOption(
                                            "backgroundRepeat",
                                            event.target.value,
                                        )
                                    }
                                >
                                    <option value="no-repeat">No repeat</option>
                                    <option value="repeat">Repeat</option>
                                    <option value="repeat-x">
                                        Repeat horizontally
                                    </option>
                                    <option value="repeat-y">
                                        Repeat vertically
                                    </option>
                                </select>
                            </label>
                            <label className="profile-generator-field">
                                <span>
                                    {OPTION_LABELS.backgroundAttachment}
                                </span>
                                <select
                                    className="input"
                                    value={options.backgroundAttachment}
                                    onChange={(event) =>
                                        updateOption(
                                            "backgroundAttachment",
                                            event.target.value,
                                        )
                                    }
                                >
                                    <option value="scroll">Scroll</option>
                                    <option value="fixed">Fixed</option>
                                    <option value="local">Local</option>
                                </select>
                            </label>
                        </div>
                    </div>

                    <div className="profile-generator-section">
                        <h2 className="advance">Advanced</h2>
                        <label
                            className="profile-generator-field"
                            htmlFor="generator-custom-css"
                        >
                            <span>Custom CSS</span>
                            <textarea
                                id="generator-custom-css"
                                className="input profile-generator-css-input"
                                value={customCss}
                                onChange={(event) => {
                                    setCustomCss(
                                        event.target.value.slice(0, 12000),
                                    );
                                    setStatus("");
                                }}
                                maxLength={12000}
                                rows={11}
                                spellCheck={false}
                                placeholder="/* Add advanced CSS here */\n.profile-page .profile-photo {\n  border-radius: 50%;\n}"
                            />
                        </label>
                        <p className="profile-generator-hint">
                            Use the profile class names from Edit Profile for
                            more detailed styling.
                        </p>
                    </div>

                    {existingCss && (
                        <div className="profile-generator-warning" role="alert">
                            <strong>Warning:</strong> this profile already has
                            custom CSS. Applying this layout will override the
                            current CSS.
                        </div>
                    )}

                    {error && (
                        <div className="profile-generator-error" role="alert">
                            {error}
                        </div>
                    )}
                    {status && (
                        <div
                            className="profile-generator-success"
                            role="status"
                        >
                            {status}
                        </div>
                    )}

                    <button
                        type="button"
                        className="btn profile-generator-apply"
                        onClick={applyToProfile}
                        disabled={pending}
                    >
                        <Save size={15} aria-hidden="true" />
                        {pending ? "Applying..." : "Apply to my profile"}
                    </button>
                </div>
            </aside>

            {!isOpen && (
                <button
                    type="button"
                    className="profile-generator-open-button"
                    onClick={() => setIsOpen(true)}
                    title="Show editor"
                    aria-label="Show editor"
                >
                    <PanelRightOpen size={17} aria-hidden="true" />
                    <span>Show editor</span>
                </button>
            )}
        </div>
    );
}
