"use client";

import { useEffect, useMemo, useRef, useState, useTransition } from "react";
import { PanelRightClose, PanelRightOpen, RotateCcw, Save } from "lucide-react";
import { applyProfileCssAction } from "@/app/actions";

type GeneratorOptions = {
  pageBackground: string;
  backgroundImage: string;
  backgroundPosition: string;
  backgroundSize: string;
  backgroundRepeat: string;
  backgroundAttachment: string;
  contentBackground: string;
  boxTitleBackground: string;
  textColor: string;
  useFontFamily: boolean;
  fontFamily: string;
  useContentWidth: boolean;
  contentWidth: string;
  borderColor: string;
  borderWidth: string;
  borderStyle: string;
  borderRadius: string;
};

const DEFAULT_OPTIONS: GeneratorOptions = {
  pageBackground: "#e5e7eb",
  backgroundImage: "",
  backgroundPosition: "center center",
  backgroundSize: "cover",
  backgroundRepeat: "no-repeat",
  backgroundAttachment: "fixed",
  contentBackground: "#ffffff",
  boxTitleBackground: "#6699cc",
  textColor: "#000000",
  useFontFamily: false,
  fontFamily: "system-ui, sans-serif",
  useContentWidth: false,
  contentWidth: "960px",
  borderColor: "#6699cc",
  borderWidth: "1px",
  borderStyle: "solid",
  borderRadius: "0px",
};

const OPTION_LABELS: Record<keyof GeneratorOptions, string> = {
  pageBackground: "Page background",
  backgroundImage: "Background image URL",
  backgroundPosition: "Image position",
  backgroundSize: "Image size",
  backgroundRepeat: "Image repeat",
  backgroundAttachment: "Image attachment",
  contentBackground: "Profile background",
  boxTitleBackground: "Section headers",
  textColor: "Text color",
  useFontFamily: "Use font family",
  fontFamily: "Font family",
  useContentWidth: "Use profile width",
  contentWidth: "Profile width",
  borderColor: "Border color",
  borderWidth: "Border width",
  borderStyle: "Border style",
  borderRadius: "Border radius",
};

function escapeCssUrl(url: string): string {
  return url.replace(/["\\\r\n]/g, (character) => `\\${character}`);
}

export function buildControlCss(options: GeneratorOptions): string {
  const backgroundImage = options.backgroundImage.trim()
    ? `  background-image: url("${escapeCssUrl(options.backgroundImage.trim())}");\n`
    : "";
  const fontFamily = options.useFontFamily
    ? `  font-family: ${options.fontFamily};\n`
    : "";
  const contentWidth = options.useContentWidth
    ? `  max-width: ${options.contentWidth};\n`
    : "";

  return `/* Generated by the profile layout generator */
.profile-page {
  background-color: ${options.pageBackground};
${backgroundImage}  background-position: ${options.backgroundPosition};
  background-size: ${options.backgroundSize};
  background-repeat: ${options.backgroundRepeat};
  background-attachment: ${options.backgroundAttachment};
  color: ${options.textColor};
${fontFamily}}

.profile-content {
${contentWidth}  background: ${options.contentBackground};
  border-color: ${options.borderColor} !important;
  border-width: ${options.borderWidth} !important;
  border-style: ${options.borderStyle} !important;
  border-radius: ${options.borderRadius} !important;
}

.profile-page .box {
  border-color: ${options.borderColor} !important;
  border-width: ${options.borderWidth} !important;
  border-style: ${options.borderStyle} !important;
  border-radius: ${options.borderRadius} !important;
}

.profile-page .box-title {
  background: ${options.boxTitleBackground} !important;
}

.profile-page .box-content {
  background: color-mix(in srgb, ${options.contentBackground} 94%, #ffffff) !important;
}
`;
}

function sanitizeStyleText(css: string): string {
  return css.replace(/<\/style/gi, "<\\/style");
}

type ParsedDecl = {
  name: string;
  value: string;
  raw: string;
};

type GeneratedBlock = {
  selector: string;
  end: number;
  declarations: ParsedDecl[];
};

const GENERATED_MARKER = "/* Generated by the profile layout generator */";

const GENERATED_SELECTORS = new Set<string>([
  ".profile-page",
  ".profile-content",
  ".profile-page .box",
  ".profile-page .box-title",
  ".profile-page .box-content",
]);

const FONT_FAMILY_PRESETS = [
  "system-ui, sans-serif",
  "Georgia, serif",
  "Verdana, sans-serif",
  "'Courier New', monospace",
];

const CONTENT_WIDTH_PRESETS = ["760px", "960px", "1100px", "100%"];

const BORDER_WIDTH_PRESETS = ["0px", "1px", "2px", "3px", "4px"];

const BORDER_STYLE_PRESETS = ["solid", "dashed", "dotted", "double"];

function parseDeclarations(body: string): ParsedDecl[] {
  const declarations: ParsedDecl[] = [];
  const pattern = /([a-zA-Z-]+)\s*:\s*([^;]+);?/gi;
  let match: RegExpExecArray | null;
  while ((match = pattern.exec(body))) {
    const valueRaw = match[2].trim();
    declarations.push({
      name: match[1].trim().toLowerCase(),
      value: valueRaw.replace(/!important$/gi, "").trim(),
      raw: `${match[1].trim()}: ${valueRaw};`,
    });
  }
  return declarations;
}

function parseHexColor(value: string): string | null {
  const match = value.match(/^#([0-9a-fA-F]{3}|[0-9a-fA-F]{6})$/);
  if (!match) return null;
  const hex = match[1];
  return hex.length === 3
    ? `#${hex
      .split("")
      .map((character) => character + character)
      .join("")}`
    : value;
}

function extractUrl(value: string): string {
  const quoted = value.match(/url\(\s*["']((?:[^"'\\]|\\.)*)["']\s*\)/);
  if (quoted) return quoted[1];
  const plain = value.match(/url\(\s*([^)]*)\s*\)/);
  return plain ? plain[1].trim() : "";
}

function colorMixBase(value: string): string | null {
  const match = value.match(/color-mix\(\s*in srgb,\s*([^ ,]+)/);
  return match ? match[1].trim() : null;
}

export function loadOptionsFromCss(css: string): {
  options: GeneratorOptions;
  customCss: string;
} {
  const defaultOptions = { ...DEFAULT_OPTIONS };
  if (!css.trim()) return { options: defaultOptions, customCss: "" };

  const markerIndex = css.indexOf(GENERATED_MARKER);
  if (markerIndex === -1)
    return { options: defaultOptions, customCss: css };

  const rulePattern = /([^{}]+)\{([^{}]*)\}/g;
  rulePattern.lastIndex = markerIndex;
  const blocks: GeneratedBlock[] = [];
  let blockEnd = markerIndex;
  let match: RegExpExecArray | null;
  while ((match = rulePattern.exec(css))) {
    const selector = match[1].replace(/\/\*[\s\S]*?\*\//g, "").trim();
    if (!GENERATED_SELECTORS.has(selector)) break;
    blocks.push({
      selector,
      end: match.index + match[0].length,
      declarations: parseDeclarations(match[2]),
    });
    blockEnd = match.index + match[0].length;
  }

  if (blocks.length === 0)
    return { options: defaultOptions, customCss: css };

  const options = { ...DEFAULT_OPTIONS };
  const leftoverBlocks: string[] = [];

  for (const block of blocks) {
    const leftovers: ParsedDecl[] = [];
    for (const decl of block.declarations) {
      let consumed = false;

      switch (block.selector) {
        case ".profile-page":
          switch (decl.name) {
            case "background-color": {
              const color = parseHexColor(decl.value);
              if (color) {
                options.pageBackground = color;
                consumed = true;
              }
              break;
            }
            case "background-image":
              options.backgroundImage =
                decl.value === "none"
                  ? ""
                  : extractUrl(decl.value);
              consumed = true;
              break;
            case "background-position":
              options.backgroundPosition = decl.value;
              consumed = true;
              break;
            case "background-size":
              options.backgroundSize = decl.value;
              consumed = true;
              break;
            case "background-repeat":
              options.backgroundRepeat = decl.value;
              consumed = true;
              break;
            case "background-attachment":
              options.backgroundAttachment = decl.value;
              consumed = true;
              break;
            case "color": {
              const color = parseHexColor(decl.value);
              if (color) {
                options.textColor = color;
                consumed = true;
              }
              break;
            }
            case "font-family":
              options.fontFamily = decl.value;
              options.useFontFamily = true;
              consumed = true;
              break;
          }
          break;
        case ".profile-content":
          switch (decl.name) {
            case "max-width":
              options.contentWidth = decl.value;
              options.useContentWidth = true;
              consumed = true;
              break;
            case "background": {
              const color = parseHexColor(decl.value);
              if (color) {
                options.contentBackground = color;
                consumed = true;
              }
              break;
            }
            case "border-color": {
              const color = parseHexColor(decl.value);
              if (color) {
                options.borderColor = color;
                consumed = true;
              }
              break;
            }
            case "border-width":
              options.borderWidth = decl.value;
              consumed = true;
              break;
            case "border-style":
              options.borderStyle = decl.value;
              consumed = true;
              break;
            case "border-radius":
              options.borderRadius = decl.value;
              consumed = true;
              break;
          }
          break;
        case ".profile-page .box":
          if (
            (decl.name === "border-color" &&
              decl.value === options.borderColor) ||
            (decl.name === "border-width" &&
              decl.value === options.borderWidth) ||
            (decl.name === "border-style" &&
              decl.value === options.borderStyle) ||
            (decl.name === "border-radius" &&
              decl.value === options.borderRadius)
          ) {
            consumed = true;
          }
          break;
        case ".profile-page .box-title":
          if (decl.name === "background") {
            const color = parseHexColor(decl.value);
            if (color) {
              options.boxTitleBackground = color;
              consumed = true;
            }
          }
          break;
        case ".profile-page .box-content":
          if (
            decl.name === "background" &&
            colorMixBase(decl.value) === options.contentBackground
          ) {
            consumed = true;
          }
          break;
      }

      if (!consumed) leftovers.push(decl);
    }

    if (leftovers.length > 0) {
      leftoverBlocks.push(
        `${block.selector} {\r\n${leftovers
          .map((decl) => `  ${decl.raw}\r\n`)
          .join("")}}`,
      );
    }
  }

  const customCss = [
    css.slice(0, markerIndex),
    ...leftoverBlocks,
    css.slice(blockEnd),
  ]
    .filter(Boolean)
    .join("\r\n")
    .trim();

  return { options, customCss };
}

export default function ProfileGenerator({
  children,
  initialCss,
}: {
  children: React.ReactNode;
  initialCss: string;
}) {
  const generatorRef = useRef<HTMLDivElement>(null);
  const [isOpen, setIsOpen] = useState(true);
  const [loadedState] = useState(() => loadOptionsFromCss(initialCss));
  const [options, setOptions] = useState<GeneratorOptions>(
    loadedState.options,
  );
  const [customCss, setCustomCss] = useState(loadedState.customCss);
  const hasExistingCss = initialCss.trim() !== "";
  const [status, setStatus] = useState("");
  const [error, setError] = useState("");
  const [pending, startTransition] = useTransition();

  const generatedCss = useMemo(() => buildControlCss(options), [options]);
  // const previewCss = `${generatedCss}\n${customCss}`;
  const previewCss = `${customCss}\n${generatedCss}`;

  useEffect(() => {
    const header = document.querySelector("header");
    const generator = generatorRef.current;
    if (!header || !generator) return;

    const updateHeaderHeight = () => {
      generator.style.setProperty(
        "--profile-generator-top",
        `${header.getBoundingClientRect().height}px`,
      );
    };

    updateHeaderHeight();
    const observer = new ResizeObserver(updateHeaderHeight);
    observer.observe(header);
    window.addEventListener("resize", updateHeaderHeight);

    return () => {
      observer.disconnect();
      window.removeEventListener("resize", updateHeaderHeight);
    };
  }, []);

  function updateOption<K extends keyof GeneratorOptions>(
    key: K,
    value: GeneratorOptions[K],
  ) {
    setOptions((current) => ({ ...current, [key]: value }));
    setStatus("");
  }

  function resetControls() {
    setOptions(DEFAULT_OPTIONS);
    setCustomCss("");
    setStatus("");
    setError("");
  }

  function applyToProfile() {
    if (
      hasExistingCss &&
      !window.confirm(
        "Your profile already has custom CSS. Applying this layout will override it. Continue?",
      )
    ) {
      return;
    }

    const formData = new FormData();
    formData.set("customCss", previewCss);
    setStatus("");
    setError("");
    startTransition(async () => {
      const result = await applyProfileCssAction(formData);
      if (result.error) setError(result.error);
      else setStatus("Applied to your profile.");
    });
  }

  return (
    <div
      ref={generatorRef}
      className={`profile-generator ${isOpen ? "is-sidebar-open" : ""}`}
    >
      <style>{sanitizeStyleText(previewCss)}</style>
      <div className="profile-generator-preview">{children}</div>

      <aside
        className="profile-generator-sidebar"
        aria-label="Profile layout controls"
      >
        <div className="profile-generator-sidebar-header">
          <div>
            <span className="profile-generator-kicker">
              LIVE EDITOR
            </span>
            <h1>Profile layout</h1>
          </div>
          <button
            type="button"
            className="profile-generator-icon-button"
            onClick={() => setIsOpen(false)}
            title="Hide editor"
            aria-label="Hide editor"
          >
            <PanelRightClose size={16} aria-hidden="true" />
            <span>Hide editor</span>
          </button>
        </div>

        <div className="profile-generator-sidebar-content">
          <div className="profile-generator-section">
            <div className="profile-generator-section-heading">
              <h2>Quick styling</h2>
              <button
                type="button"
                className="profile-generator-reset"
                onClick={resetControls}
                title="Reset layout controls"
              >
                <RotateCcw size={13} aria-hidden="true" />
                Reset
              </button>
            </div>
            <div className="profile-generator-control-grid">
              {(
                [
                  "pageBackground",
                  "contentBackground",
                  "boxTitleBackground",
                  "textColor",
                  "borderColor",
                ] as const
              ).map((key) => (
                <label
                  key={key}
                  className="profile-generator-color-control"
                >
                  <span>{OPTION_LABELS[key]}</span>
                  <span className="profile-generator-color-row">
                    <input
                      type="color"
                      value={options[key]}
                      onChange={(event) =>
                        updateOption(
                          key,
                          event.target.value,
                        )
                      }
                      aria-label={OPTION_LABELS[key]}
                    />
                    <code>{options[key]}</code>
                  </span>
                </label>
              ))}
            </div>

            <div className="profile-generator-subsection">
              <label className="profile-generator-check">
                <input
                  type="checkbox"
                  checked={options.useFontFamily}
                  onChange={(event) =>
                    updateOption(
                      "useFontFamily",
                      event.target.checked,
                    )
                  }
                />
                <span>{OPTION_LABELS.useFontFamily}</span>
              </label>
              {options.useFontFamily && (
                <label className="profile-generator-field">
                  <span>{OPTION_LABELS.fontFamily}</span>
                  <select
                    className="input"
                    value={options.fontFamily}
                    onChange={(event) =>
                      updateOption(
                        "fontFamily",
                        event.target.value,
                      )
                    }
                  >
                    {!FONT_FAMILY_PRESETS.includes(
                      options.fontFamily,
                    ) && (
                        <option
                          value={options.fontFamily}
                        >
                          {options.fontFamily}
                        </option>
                      )}
                    <option value="system-ui, sans-serif">
                      System sans
                    </option>
                    <option value="Georgia, serif">
                      Georgia
                    </option>
                    <option value="Verdana, sans-serif">
                      Verdana
                    </option>
                    <option value="'Courier New', monospace">
                      Courier New
                    </option>
                  </select>
                </label>
              )}
            </div>

            <div className="profile-generator-subsection">
              <label className="profile-generator-check">
                <input
                  type="checkbox"
                  checked={options.useContentWidth}
                  onChange={(event) =>
                    updateOption(
                      "useContentWidth",
                      event.target.checked,
                    )
                  }
                />
                <span>{OPTION_LABELS.useContentWidth}</span>
              </label>
              {options.useContentWidth && (
                <label className="profile-generator-field">
                  <span>{OPTION_LABELS.contentWidth}</span>
                  <select
                    className="input"
                    value={options.contentWidth}
                    onChange={(event) =>
                      updateOption(
                        "contentWidth",
                        event.target.value,
                      )
                    }
                  >
                    {!CONTENT_WIDTH_PRESETS.includes(
                      options.contentWidth,
                    ) && (
                        <option
                          value={options.contentWidth}
                        >
                          {options.contentWidth}
                        </option>
                      )}
                    <option value="760px">
                      Compact (760px)
                    </option>
                    <option value="960px">
                      Classic (960px)
                    </option>
                    <option value="1100px">
                      Wide (1100px)
                    </option>
                    <option value="100%">Full width</option>
                  </select>
                </label>
              )}
            </div>

            <div className="profile-generator-subsection">
              <h3>Border styling</h3>
              <div className="profile-generator-border-grid">
                <label className="profile-generator-field">
                  <span>{OPTION_LABELS.borderWidth}</span>
                  <select
                    className="input"
                    value={options.borderWidth}
                    onChange={(event) =>
                      updateOption(
                        "borderWidth",
                        event.target.value,
                      )
                    }
                  >
                    {!BORDER_WIDTH_PRESETS.includes(
                      options.borderWidth,
                    ) && (
                        <option
                          value={options.borderWidth}
                        >
                          {options.borderWidth}
                        </option>
                      )}
                    <option value="0px">None</option>
                    <option value="1px">1px</option>
                    <option value="2px">2px</option>
                    <option value="3px">3px</option>
                    <option value="4px">4px</option>
                  </select>
                </label>
                <label className="profile-generator-field">
                  <span>{OPTION_LABELS.borderStyle}</span>
                  <select
                    className="input"
                    value={options.borderStyle}
                    onChange={(event) =>
                      updateOption(
                        "borderStyle",
                        event.target.value,
                      )
                    }
                  >
                    {!BORDER_STYLE_PRESETS.includes(
                      options.borderStyle,
                    ) && (
                        <option
                          value={options.borderStyle}
                        >
                          {options.borderStyle}
                        </option>
                      )}
                    <option value="solid">Solid</option>
                    <option value="dashed">Dashed</option>
                    <option value="dotted">Dotted</option>
                    <option value="double">Double</option>
                  </select>
                </label>
                {/* <label className="profile-generator-field">
                                    <span>{OPTION_LABELS.borderRadius}</span>
                                    <select
                                        className="input"
                                        value={options.borderRadius}
                                        onChange={(event) =>
                                            updateOption(
                                                "borderRadius",
                                                event.target.value,
                                            )
                                        }
                                    >
                                        <option value="0px">Square</option>
                                        <option value="4px">Small</option>
                                        <option value="8px">Medium</option>
                                        <option value="16px">Large</option>
                                        <option value="999px">Pill</option>
                                    </select>
                                </label> */}
              </div>
            </div>
          </div>

          <div className="profile-generator-section">
            <div className="profile-generator-section-heading">
              <h2>Page background</h2>
            </div>
            <label className="profile-generator-field">
              <span>{OPTION_LABELS.backgroundImage}</span>
              <input
                className="input"
                type="url"
                value={options.backgroundImage}
                onChange={(event) =>
                  updateOption(
                    "backgroundImage",
                    event.target.value,
                  )
                }
                placeholder="https://example.com/background.jpg"
                maxLength={500}
              />
            </label>
            <div className="profile-generator-border-grid profile-generator-background-settings">
              <label className="profile-generator-field">
                <span>{OPTION_LABELS.backgroundPosition}</span>
                <select
                  className="input"
                  value={options.backgroundPosition}
                  onChange={(event) =>
                    updateOption(
                      "backgroundPosition",
                      event.target.value,
                    )
                  }
                >
                  <option value="center top">
                    Top center
                  </option>
                  <option value="center center">
                    Center
                  </option>
                  <option value="left top">Top left</option>
                  <option value="right top">Top right</option>
                  <option value="center bottom">
                    Bottom center
                  </option>
                </select>
              </label>
              <label className="profile-generator-field">
                <span>{OPTION_LABELS.backgroundSize}</span>
                <select
                  className="input"
                  value={options.backgroundSize}
                  onChange={(event) =>
                    updateOption(
                      "backgroundSize",
                      event.target.value,
                    )
                  }
                >
                  <option value="cover">Cover</option>
                  <option value="contain">Contain</option>
                  <option value="auto">Original size</option>
                  <option value="100% auto">
                    Stretch width
                  </option>
                </select>
              </label>
              <label className="profile-generator-field">
                <span>{OPTION_LABELS.backgroundRepeat}</span>
                <select
                  className="input"
                  value={options.backgroundRepeat}
                  onChange={(event) =>
                    updateOption(
                      "backgroundRepeat",
                      event.target.value,
                    )
                  }
                >
                  <option value="no-repeat">No repeat</option>
                  <option value="repeat">Repeat</option>
                  <option value="repeat-x">
                    Repeat horizontally
                  </option>
                  <option value="repeat-y">
                    Repeat vertically
                  </option>
                </select>
              </label>
              <label className="profile-generator-field">
                <span>
                  {OPTION_LABELS.backgroundAttachment}
                </span>
                <select
                  className="input"
                  value={options.backgroundAttachment}
                  onChange={(event) =>
                    updateOption(
                      "backgroundAttachment",
                      event.target.value,
                    )
                  }
                >
                  <option value="scroll">Scroll</option>
                  <option value="fixed">Fixed</option>
                  <option value="local">Local</option>
                </select>
              </label>
            </div>
          </div>

          <div className="profile-generator-section">
            <h2 className="advance">Advanced</h2>
            <label
              className="profile-generator-field"
              htmlFor="generator-custom-css"
            >
              <span>Custom CSS</span>
              <textarea
                id="generator-custom-css"
                className="input profile-generator-css-input"
                value={customCss}
                onChange={(event) => {
                  setCustomCss(
                    event.target.value.slice(0, 20000),
                  );
                  setStatus("");
                }}
                maxLength={20000}
                rows={11}
                spellCheck={false}
                placeholder="/* Add advanced CSS here */\n.profile-page .profile-photo {\n  border-radius: 50%;\n}"
              />
            </label>
            <p className="profile-generator-hint">
              Use the profile class names from Edit Profile for
              more detailed styling.
            </p>
          </div>

          {hasExistingCss && (
            <div className="profile-generator-warning" role="alert">
              <strong>Warning:</strong> this profile already has
              custom CSS. Applying this layout will override the
              current CSS.
            </div>
          )}

          {error && (
            <div className="profile-generator-error" role="alert">
              {error}
            </div>
          )}
          {status && (
            <div
              className="profile-generator-success"
              role="status"
            >
              {status}
            </div>
          )}

          <button
            type="button"
            className="btn profile-generator-apply"
            onClick={applyToProfile}
            disabled={pending}
          >
            <Save size={15} aria-hidden="true" />
            {pending ? "Applying..." : "Apply to my profile"}
          </button>
        </div>
      </aside>

      {!isOpen && (
        <button
          type="button"
          className="profile-generator-open-button"
          onClick={() => setIsOpen(true)}
          title="Show editor"
          aria-label="Show editor"
        >
          <PanelRightOpen size={17} aria-hidden="true" />
          <span>Show editor</span>
        </button>
      )}
    </div>
  );
}
